// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtAgAUfyI9tQX9XXCSPRTerqQsBh1LbXk',
    appId: '1:841065984080:web:74416838864f3d38836155',
    messagingSenderId: '841065984080',
    projectId: 'salesgo-49e56',
    authDomain: 'salesgo-49e56.firebaseapp.com',
    storageBucket: 'salesgo-49e56.firebasestorage.app',
    measurementId: 'G-VZ6MHV30BT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0FuETZfLqhEF9Tglmo2DqOYoefa6UyjI',
    appId: '1:841065984080:android:e356f68a50456f32836155',
    messagingSenderId: '841065984080',
    projectId: 'salesgo-49e56',
    storageBucket: 'salesgo-49e56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZLay0tHq0wLc0rAJ_z0KGA_9aW8fpv8U',
    appId: '1:841065984080:ios:2b7a1fa1b210daba836155',
    messagingSenderId: '841065984080',
    projectId: 'salesgo-49e56',
    storageBucket: 'salesgo-49e56.firebasestorage.app',
    iosBundleId: 'net.icloudsolutions.salesgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZLay0tHq0wLc0rAJ_z0KGA_9aW8fpv8U',
    appId: '1:841065984080:ios:2b7a1fa1b210daba836155',
    messagingSenderId: '841065984080',
    projectId: 'salesgo-49e56',
    storageBucket: 'salesgo-49e56.firebasestorage.app',
    iosBundleId: 'net.icloudsolutions.salesgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtAgAUfyI9tQX9XXCSPRTerqQsBh1LbXk',
    appId: '1:841065984080:web:d629584b20a21e2c836155',
    messagingSenderId: '841065984080',
    projectId: 'salesgo-49e56',
    authDomain: 'salesgo-49e56.firebaseapp.com',
    storageBucket: 'salesgo-49e56.firebasestorage.app',
    measurementId: 'G-ESP4M4W4W9',
  );
}
