platform :ios, '13.0'

# ignore toutes les architectures simulées pour éviter les erreurs
install! 'cocoapods', :deterministic_uuids => false

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
