# ios/Podfile
platform :ios, '13.0'

# Fait fonctionner Flipper (outil de debug) si vous l’activez dans flutter
# Désactivez-le si vous ne l’utilisez pas
ENV['FLUTTER_FRAMEWORK_DIR'] ||= File.join(__dir__, '..', 'flutter', 'bin', 'cache', 'artifacts', 'engine', 'ios')

# Utilisé par Codemagic et Flutter
require_relative '../.flutter-plugins'
require_relative '../.flutter-plugins-dependencies'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

# Post install : règle les problèmes liés à Xcode 14+
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
