name: Build iOS

on:
  push:
    branches: [ 1.3.7 ]
  pull_request:
    branches: [ 1.3.7 ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Build iOS
      run: flutter build ios --release --no-codesign
    
    - name: Archive IPA
      if: github.ref == 'refs/heads/main'
      run: |
        cd ios
        xcodebuild -workspace Runner.xcworkspace -scheme Runner -archivePath build/Runner.xcarchive archive
        xcodebuild -exportArchive -archivePath build/Runner.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath build/Release -allowProvisioningUpdates
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Runner.ipa
        path: ios/build/Release/Runner.ipa
